import LeftMenuForAdmin from "@/components/LeftMenu/LeftMenuForAdmin";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard - Spotify",
    description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex h-screen">
            <div className="w-65">
                <LeftMenuForAdmin />
            </div>
            <ScrollArea className="h-[calc(100vh)] flex-1 px-3">
                <div className="bg-(image:--gradient-color-login) px-6">
                    {children}
                </div>
            </ScrollArea>
        </div>
    );
}
