import LeftMenuForAdmin from "@/components/LeftMenu/LeftMenuForAdmin";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard - Spotify",
    description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex h-screen">
            <div className="w-65">
                <LeftMenuForAdmin />
            </div>
            <div className="flex-1 bg-(image:--gradient-color-login) px-6">
                {children}
            </div>
        </div>
    );
}
